// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/robwestbrook/go-mylife/views/layouts"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Base().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"w-full px-8 py-16 bg-gray-100 xl:px-8\"><div class=\"max-w-5xl mx-auto items-center\"><div class=\"flex flex-col justify-center items-center md:flex-row\"><div class=\"w-full mt-16 md:mt-0 md:w-2/5\"><div class=\"relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7\" data-rounded=\"rounded-lg\" data-rounded-max=\"rounded-full\"><h3 class=\"mb-6 text-2xl font-medium text-center\">Log in to your Account</h3><input type=\"text\" name=\"email\" id=\"email\" class=\"block w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none\" data-rounded=\"rounded-lg\" data-primary=\"blue-500\" placeholder=\"Email address\"> <input type=\"password\" name=\"password\" id=\"password\" class=\"block w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none\" data-rounded=\"rounded-lg\" data-primary=\"blue-500\" placeholder=\"Password\"><div class=\"block\"><button class=\"w-full px-3 py-4 font-medium text-white bg-blue-600 rounded-lg\" data-primary=\"blue-600\" data-rounded=\"rounded-lg\">Log In</button></div><p class=\"w-full mt-4 text-sm text-center text-gray-500\">Don't have an account? <a href=\"#_\" class=\"text-blue-500 underline\">Sign up here</a></p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
